### ISSUE TITLE
Search behavior has changed? Not getting expected results

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1297]
There seems to be some changes in the search behavior recently. I'm not longer getting expected results, based on previous behavior

This [link](https://maproulette.org/browse/challenges?challengeSearch=124.85549926757814%2C11.088291412779482%2C124.86678600311281%2C11.094387379661734&keywords=osmapaaralan&location=intersectingMapBounds), for example is used to open MapRoulette to any given coordinates and display all tasks available from the `osmapaaralan` challenge.

Here are some observations:

### Search results are now significantly slower to appear
![image](https://user-images.githubusercontent.com/5821688/86421286-0804a200-bd0c-11ea-86ba-923e9087da60.png)

- Clicking on clustered results , the map will zoom in and then display no markers for taks that are supposed to be available

### Browsing the same area manually shows a different number of markers for the challenge
![image](https://user-images.githubusercontent.com/5821688/86421330-35515000-bd0c-11ea-9144-9d854fbaa96b.png)
- Manually browsing tasks , and clicking on markers works as expected.

**Comment by krotstan** [comment]
Addressed by maproulette/maproulette2#811

**Comment by govvin** [comment]
Still getting unexpected results. The link in the original post will show that tasks are available in the area, but when markers are clicked, they disappear.

Also, it seems like keywords (to limit search to certain challenges) are being ignored, and maybe that's why the search results are taking longer to appear?

For example, this search link: https://maproulette.org/browse/challenges?challengeSearch=124.23950850963594%2C7.190261702587633%2C124.24515187740327%2C7.193343264569108&keywords=osmapaaralan&location=intersectingMapBounds displays tasks that doesn't use the "osmapaaralan" keyword.

![image](https://user-images.githubusercontent.com/5821688/87621354-33977b80-c753-11ea-9f27-0ccca2f359e2.png)

**Comment by nrotstan** [comment]
Hi @govvin this will be fixed in the next release. I think the issue got closed when the fix was merged in, but it hasn't yet been released.

I will reopen the issue until it's deployed to maproulette.org to avoid any further confusion. Thanks for staying on top of things!

**Comment by nrotstan** [comment]
The fix is now deployed to maproulette.org -- please let me know if you continue to experience problems.

**Comment by govvin** [comment]
I confirm that this is now working as expected, and getting the search results seem to be back to its previous speed.
